sudo: false
language: python
python:
  - "3.7"
  - "3.8"
cache:
  pip: true
env:
  - DJANGO_VERSION=2.1.1 BINDER_TEST_MYSQL=0
  - DJANGO_VERSION=3.1.4 BINDER_TEST_MYSQL=0
  - DJANGO_VERSION=2.1.1 BINDER_TEST_MYSQL=1
  - DJANGO_VERSION=3.1.4 BINDER_TEST_MYSQL=1
install:
  - pip install -q psycopg2 Pillow django-request-id requests django==$DJANGO_VERSION
  - pip install flake8 codecov coverage
script:
  - flake8 binder
  - coverage run --include="binder/*" setup.py test
before_script:
  - psql -c 'create database "binder-test";' -U postgres
  - mysql -e 'CREATE DATABASE `binder-test`;'
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql
  - export CY_RUNNING_INSIDE_TRAVIS=1
services:
  - postgresql
  - mysql
addons:
  postgresql: "9.6"
after_success:
  - codecov
