name: Continuous Integration

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}

    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
        django-version: ["2.1.1", "3.1.4"]
        database-engine: ["postgres", "mysql"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve cached venv
        uses: actions/cache@v1
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ matrix.python-version }}-venv-${{ hashFiles('setup.py') }}

      - name: Install package
        run: |
          python -m venv .venv
          .venv/bin/pip install -q psycopg2 Pillow django-request-id requests flake8 codecov coverage django==${{ matrix.django-version }}
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run linting
        run: .venv/bin/flake8 binder

      - name: Install postgres client
        run: |
          sudo apt-get install postgres-client
        if: matrix.database-engine == 'postgres'

      - name: Prepare postgres database
        run: |
          psql -c 'CREATE DATABASE "binder-test";' -h postgres -U postgres
        if: matrix.database-engine == 'postgres'

      - name: Install mysql client
        run: |
          sudo apt-get install mariadb-client
        if: matrix.database-engine == 'mysql'

      - name: Prepare mysql database
        run: |
          mysql -e 'CREATE DATABASE `binder-test`; -h mysql'
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -h mysql mysql
        if: matrix.database-engine == 'mysql'

      - name: Run tests
        run: |
          .venv/bin/coverage run --include="binder/*" setup.py test
        env:
          BINDER_TEST_MYSQL: ${{ matrix.database-engine == 'mysql' && 1 || 0 }}
          CY_RUNNING_INSIDE_CI: 1
          CY_DB_HOST: ${{ matrix.database-engine }}

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
